import { rabbitChannel } from "../config/rabbitmq.js"
import { ORDER_CREATED_EVENT, ORDER_INBOUND_DLQ_EXCHANGE, ORDER_INBOUND_DLQ_QUEUE, ORDER_INBOUND_DLQ_ROUTING_KEY, ORDER_INBOUND_QUEUE, ORDER_INBOUND_RETRY_EXCHANGE, ORDER_INBOUND_RETRY_QUEUE, ORDER_INBOUND_RETRY_ROUTING_KEY, PAYMENT_INTERNAL_DLQ_EXCHANGE, PAYMENT_INTERNAL_DLQ_QUEUE, PAYMENT_INTERNAL_DLQ_ROUTING_KEY, PAYMENT_INTERNAL_QUEUE, PAYMENT_INTERNAL_RETRY_EXCHANGE, PAYMENT_INTERNAL_RETRY_QUEUE, PAYMENT_INTERNAL_RETRY_ROUTING_KEY } from "./constants.js";

export const setupBindings = async () => {
  await rabbitChannel.bindQueue(PAYMENT_INTERNAL_QUEUE, PAYMENT_EVENTS_EXCHANGE, "payment.internal.*");
  await rabbitChannel.bindQueue(PAYMENT_INTERNAL_RETRY_QUEUE, PAYMENT_INTERNAL_RETRY_EXCHANGE, PAYMENT_INTERNAL_RETRY_ROUTING_KEY);
  await rabbitChannel.bindQueue(PAYMENT_INTERNAL_DLQ_QUEUE, PAYMENT_INTERNAL_DLQ_EXCHANGE, PAYMENT_INTERNAL_DLQ_ROUTING_KEY);

  await rabbitChannel.bindQueue(ORDER_INBOUND_QUEUE, ORDER_EVENTS_EXCHANGE, ORDER_CREATED_EVENT);
  await rabbitChannel.bindQueue(ORDER_INBOUND_RETRY_QUEUE, ORDER_INBOUND_RETRY_EXCHANGE, ORDER_INBOUND_RETRY_ROUTING_KEY);
  await rabbitChannel.bindQueue(ORDER_INBOUND_DLQ_QUEUE, ORDER_INBOUND_DLQ_EXCHANGE, ORDER_INBOUND_DLQ_ROUTING_KEY);
}
