import { rabbitChannel } from "../config/rabbitmq.js"
import { ORDER_EVENTS_EXCHANGE, ORDER_INTERNAL_DLQ_EXCHANGE, ORDER_INTERNAL_DLQ_QUEUE, ORDER_INTERNAL_DLQ_ROUTING_KEY, ORDER_INTERNAL_QUEUE, ORDER_INTERNAL_RETRY_EXCHANGE, ORDER_INTERNAL_RETRY_QUEUE, ORDER_INTERNAL_RETRY_ROUTING_KEY, PAYMENT_EVENTS_EXCHANGE, PAYMENT_INBOUND_DLQ_EXCHANGE, PAYMENT_INBOUND_DLQ_QUEUE, PAYMENT_INBOUND_DLQ_ROUTING_KEY, PAYMENT_INBOUND_QUEUE, PAYMENT_INBOUND_RETRY_EXCHANGE, PAYMENT_INBOUND_RETRY_QUEUE, PAYMENT_INBOUND_RETRY_ROUTING_KEY, PAYMENT_STATUS_EVENT } from "./constants.js";

export const setupBindings = async () => {

    //ORDER
    //  order.# ---> order.created, order.cancelled, order.internal.hersey
    await rabbitChannel.bindQueue(ORDER_INTERNAL_QUEUE, ORDER_EVENTS_EXCHANGE, "order.#");
    await rabbitChannel.bindQueue(ORDER_INTERNAL_RETRY_QUEUE, ORDER_INTERNAL_RETRY_EXCHANGE, ORDER_INTERNAL_RETRY_ROUTING_KEY);
    await rabbitChannel.bindQueue(ORDER_INTERNAL_DLQ_QUEUE, ORDER_INTERNAL_DLQ_EXCHANGE, ORDER_INTERNAL_DLQ_ROUTING_KEY);

    //ORDER-PAYMENT CONNECTED
    await rabbitChannel.bindQueue(PAYMENT_INBOUND_QUEUE, PAYMENT_EVENTS_EXCHANGE, PAYMENT_STATUS_EVENT);
    await rabbitChannel.bindQueue(PAYMENT_INBOUND_RETRY_QUEUE, PAYMENT_INBOUND_RETRY_EXCHANGE, PAYMENT_INBOUND_RETRY_ROUTING_KEY);
    await rabbitChannel.bindQueue(PAYMENT_INBOUND_DLQ_QUEUE, PAYMENT_INBOUND_DLQ_EXCHANGE, PAYMENT_INBOUND_DLQ_ROUTING_KEY);
}