import { rabbitChannel } from "../config/rabbitmq.js"
import { ORDER_DLQ_EXCHANGE, ORDER_DLQ_QUEUE, ORDER_DLQ_ROUTING_KEY, ORDER_EVENTS_EXCHANGE, ORDER_PAYMENT_DLQ_EXCHANGE, ORDER_PAYMENT_DLQ_QUEUE, ORDER_PAYMENT_DLQ_ROUTING_KEY, ORDER_PAYMENT_QUEUE, ORDER_PAYMENT_RETRY_EXCHANGE, ORDER_PAYMENT_RETRY_QUEUE, ORDER_PAYMENT_RETRY_ROUTING_KEY, ORDER_PAYMENT_ROUTING_KEY, ORDER_QUEUE, ORDER_RETRY_EXCHANGE, ORDER_RETRY_QUEUE, ORDER_RETRY_ROUTING_KEY, PAYMENT_EVENTS_EXCHANGE } from "./constants.js";

export const setupBindings = async () => {

    //ORDER
    await rabbitChannel.bindQueue(ORDER_QUEUE, ORDER_EVENTS_EXCHANGE, "order.*");
    await rabbitChannel.bindQueue(ORDER_RETRY_QUEUE, ORDER_RETRY_EXCHANGE, ORDER_RETRY_ROUTING_KEY);
    await rabbitChannel.bindQueue(ORDER_DLQ_QUEUE, ORDER_DLQ_EXCHANGE, ORDER_DLQ_ROUTING_KEY);

    //ORDER-PAYMENT CONNECTED
    await rabbitChannel.bindQueue(ORDER_PAYMENT_QUEUE, PAYMENT_EVENTS_EXCHANGE, ORDER_PAYMENT_ROUTING_KEY);

    //ORDER-PAYMENT
    await rabbitChannel.bindQueue(ORDER_PAYMENT_RETRY_QUEUE, ORDER_PAYMENT_RETRY_EXCHANGE, ORDER_PAYMENT_RETRY_ROUTING_KEY);
    await rabbitChannel.bindQueue(ORDER_PAYMENT_DLQ_QUEUE, ORDER_PAYMENT_DLQ_EXCHANGE, ORDER_PAYMENT_DLQ_ROUTING_KEY);


}